In [118]:
import os
import pandas as pd
from dotenv import load_dotenv
from gsheet_loader import load_sheet
load_dotenv()

True

In [119]:
# Load a Google Sheet
url = os.environ["GOOGLE_SHEET_URL"]
data = load_sheet(url)
df = pd.read_csv(data)
df.head()

,Timestamp,A1. Your age (আপনার বয়স),A2. You are (আপনি ),A3. Your religion(আপনার ধর্ম),A4. Your marital status(আপনার বৈবাহিক অবস্থা),A5. Where do you live?(আপনি কোথায় বসবাস করেন ?),A6. Occupation(পেশা),B1. What kind of family do you live in?(আপনি কি ধরনের পরিবারে বসবাস করেন?),B2. How much time do you typically spend with your family each day? (আপনি প্রতিদিন সাধারণ কত সময় আপনার পরিবারের সাথে কাটান?)\n____________ Hours(ঘন্টা),B3. How is your relationship with your family?(আপনার পরিবারের সাথে আপনার সম্পর্ক কেমন?)\n,...,"G6. Do you sometimes or often experience panic attacks(racing heartbeat, shortness of breath?) (আপনি কি কখনো আতঙ্ক বা প্যানিক অ্যাটাক(দ্রুত হৃদস্পন্দন, শ্বাসকষ্ট) অনুভব করেন?)",G7.What type are you according to your behavior?(আপনার আচরণ অনুযায়ী আপনি কোন ধরণের?),"G8.Do you watch reels because of an addiction, even if you don't have the desire to watch them? (আপনার রিলস দেখার ইচ্ছা না থাকলেও আসক্তির কারণে আপনি কি রিলস দেখেন?)",H1. Does your mental state change after watching Facebook viral reels?(ফেসবুক এ ভাইরাল রিলস দেখার পরে কি আপনার মানসিক অবস্থার পরিবর্তন হয়?),"H2. Does watching tragic or entertaining content on Facebook Reels have any effect on your mental state (excitement, enthusiasm,anxiety)?(ফেসবুক রিলস এ মর্মান্তিক বা বিনোদনমূলক বিষয়বস্তু দেখলে সেটা কি আপনার মানসিক অবস্থার (যেমন: উত্তেজনা,উদ্দীপনা, উদ্বেগ) উপর কোনো প্রভাব ফেলে?)\n",H3. Do you become distracted or inattentive after watching viral reels on Facebook?(ফেসবুক এ ভাইরাল রিলস দেখার পর আপনি কি বিভ্রান্ত বা অমনোযোগী হয়ে যান?),H4. Does your brain feel extra pressure after watching viral content?(ভাইরাল কনটেন্ট দেখার পর কি আপনার মস্তিষ্কে অতিরিক্ত চাপ অনুভব হয়?),H5. Does watching viral reels on Facebook before bed change your sleep quality?(ঘুমানোর আগে ফেসবুকে ভাইরাল রিলস দেখার কারণে কি আপনার ঘুমের মানের কোনো পরিবর্তন হয়?),H6. Does watching emotional reels make you lose focus on studies or work?(আবেগপ্রবণ রিলস দেখার পর কি আপনার পড়াশোনা বা কাজের প্রতি মনোযোগ কমে যায়?),"H7. When a viral reel sparks excitement or curiosity in you, do you feel inclined to watch more reels related to that?(যখন কোনো ভাইরাল রিলস আপনার মধ্যে উত্তেজনা বা কৌতূহল জাগিয়ে তোলে, তখন কি আপনি সেই সম্পর্কিত আরও রিলস দেখার জন্য আগ্রহী হন?)"
0,12/15/2025 0:37:42,24,Male(ছেলে),Islam (ইসলাম),Married (বিবাহিত),Urban Area (শহুরে এলাকা),Student (স্টুডেন্ট),Single family(একক পরিবার ),3,Good (ভালো),...,Sometimes (মাঝে মাঝে),Extrovert (বহির্মুখী),Sometimes (মাঝে মাঝে),Some Change (কিছুটা পরিবর্তন হয়),Negative Impact (নেতিবাচক প্রভাব),Sometimes (মাঝে মাঝে),Moderate Stress (মাঝারি চাপ অনুভব হয়),Slight Change in Sleep Quality (ঘুমের মান কিছু...,Lose Focus Frequently (অত্যধিক মনোযোগ হারায়),Sometimes Interested (মাঝে মাঝে আগ্রহ হয়)
1,12/15/2025 0:51:14,28,Male(ছেলে),Islam (ইসলাম),Unmarried (অবিবাহিত),Urban Area (শহুরে এলাকা),Service Holder (চাকুরীজীবী),Joint Family (যৌথ পরিবার),10 min max,Very Good (খুবই ভালো),...,Never (কখনো না),Introvert (অন্তর্মুখী),Never (কখনো না),No Change (পরিবর্তন নেই),No Impact (কোনো প্রভাব পড়ে না),Never (কখনো না),No Stress (চাপ অনুভব হয় না),Not Sure (নিশ্চিত না),Do Not Lose Focus (মনোযোগ কমে না),Rarely Interested (খুব কম আগ্রহ হয়)
2,12/15/2025 0:54:55,25,Female(মেয়ে),Islam (ইসলাম),Unmarried (অবিবাহিত),Urban Area (শহুরে এলাকা),Student (স্টুডেন্ট),Single family(একক পরিবার ),5/6,Very Good (খুবই ভালো),...,Sometimes (মাঝে মাঝে),Introvert (অন্তর্মুখী),Always (সবসময়),Some Change (কিছুটা পরিবর্তন হয়),Not Sure (নিশ্চিত না),Sometimes (মাঝে মাঝে),No Stress (চাপ অনুভব হয় না),Not Sure (নিশ্চিত না),Lose Focus Sometimes (মাঝে মাঝে মনোযোগ হারায়),More Interest in Watching Reels (আরও রিলস দেখা...
3,12/15/2025 1:01:26,25,Male(ছেলে),Islam (ইসলাম),Married (বিবাহিত),Urban Area (শহুরে এলাকা),Student (স্টুডেন্ট),Joint Family (যৌথ পরিবার),2/3 Hours,Moderate (মাঝারি),...,Never (কখনো না),Ambivert (মাঝামাঝি),Sometimes (মাঝে মাঝে),Some Change (কিছুটা পরিবর্তন হয়),Not Sure (নিশ্চিত না),Never (কখনো না),No Stress (চাপ অনুভব হয় না),Not Sure (নিশ্চিত না),Do Not Lose Focus (মনোযোগ কমে না),Sometimes Interested (মাঝে মাঝে আগ্রহ হয়)
4,12/15/2025 1:13:01,25,Female(মেয়ে),Islam (ইসলাম),Unmarried (অবিবাহিত),Urban Area (শহুরে এলাকা),Student (স্টুডেন্ট),Single family(একক পরিবার ),0,Good (ভালো),...,Sometimes (মাঝে মাঝে),Ambivert (মাঝামাঝি),Always (সবসময়),Some Change (কিছুটা পরিবর্তন হয়),Not Sure (নিশ্চিত না),Rarely (খুব কম),Low Stress (সামান্য চাপ অনুভব হয়),Slight Change in Sleep Quality (ঘুমের মান কিছু...,Lose Focus Rarely (খুব কম মনোযোগ হারায়),Sometimes Interested (মাঝে মাঝে আগ্রহ হয়)

In [120]:
# Rename columns to short, code-based names (e.g. A1_age, A2_gender, ...)
import re

# Human-readable label for each question code (based on the English question text)
code_labels = {
    "A1": "age",
    "A2": "gender",
    "A3": "religion",
    "A4": "marital_status",
    "A5": "residence",
    "A6": "occupation",
    "B1": "family_type",
    "B2": "family_time_hours",
    "B3": "family_relationship",
    "B4": "in_person_feeling",
    "C1": "height",
    "C2": "weight",
    "C3": "sitting_duration",
    "C4": "physical_problems",
    "D1": "years_watching",
    "D2": "daily_watch_time",
    "D3": "peak_watch_time",
    "D4": "multitasking_while_watching",
    "E1": "sleep_hours",
    "E2": "sleep_trouble",
    "E3": "exercise_involvement",
    "E4": "substance_use",
    "F1": "attention_decreased",
    "F2": "memory_reduced",
    "F3": "learning_interest_decreased",
    "F4": "performance_affected",
    "G1": "mood_swings",
    "G2": "fomo_anxiety",
    "G3": "social_comparison",
    "G4": "social_isolation",
    "G5": "mental_stress",
    "G6": "panic_attacks",
    "G7": "behavior_type",
    "G8": "addictive_watching",
    "H1": "mental_state_change",
    "H2": "content_type_effect",
    "H3": "distraction_after_viral",
    "H4": "brain_pressure",
    "H5": "sleep_quality_change",
    "H6": "emotional_reels_focus_loss",
    "H7": "curiosity_driven_rewatch",
}

code_pattern = re.compile(r"^\s*([A-H]\d{1,2})\s*[.)]")


def clean_column_name(col: str) -> str:
    if col.strip().lower() == "timestamp":
        return "timestamp"
    match = code_pattern.match(col)
    if match:
        code = match.group(1)
        label = code_labels.get(code)
        if label:
            return f"{code}_{label}"
    return col


df = df.rename(columns=clean_column_name)
df = df.drop(columns=["timestamp"])
df.columns.tolist()

['A1_age',
 'A2_gender',
 'A3_religion',
 'A4_marital_status',
 'A5_residence',
 'A6_occupation',
 'B1_family_type',
 'B2_family_time_hours',
 'B3_family_relationship',
 'B4_in_person_feeling',
 'C1_height',
 'C2_weight',
 'C3_sitting_duration',
 'C4_physical_problems',
 'D1_years_watching',
 'D2_daily_watch_time',
 'D3_peak_watch_time',
 'D4_multitasking_while_watching',
 'E1_sleep_hours',
 'E2_sleep_trouble',
 'E3_exercise_involvement',
 'E4_substance_use',
 'F1_attention_decreased',
 'F2_memory_reduced',
 'F3_learning_interest_decreased',
 'F4_performance_affected',
 'G1_mood_swings',
 'G2_fomo_anxiety',
 'G3_social_comparison',
 'G4_social_isolation',
 'G5_mental_stress',
 'G6_panic_attacks',
 'G7_behavior_type',
 'G8_addictive_watching',
 'H1_mental_state_change',
 'H2_content_type_effect',
 'H3_distraction_after_viral',
 'H4_brain_pressure',
 'H5_sleep_quality_change',
 'H6_emotional_reels_focus_loss',
 'H7_curiosity_driven_rewatch']

In [121]:
df.head()

,A1_age,A2_gender,A3_religion,A4_marital_status,A5_residence,A6_occupation,B1_family_type,B2_family_time_hours,B3_family_relationship,B4_in_person_feeling,...,G6_panic_attacks,G7_behavior_type,G8_addictive_watching,H1_mental_state_change,H2_content_type_effect,H3_distraction_after_viral,H4_brain_pressure,H5_sleep_quality_change,H6_emotional_reels_focus_loss,H7_curiosity_driven_rewatch
0,24,Male(ছেলে),Islam (ইসলাম),Married (বিবাহিত),Urban Area (শহুরে এলাকা),Student (স্টুডেন্ট),Single family(একক পরিবার ),3,Good (ভালো),Somewhat Comfortable (কিছুটা স্বাচ্ছন্দ্যবোধ করি),...,Sometimes (মাঝে মাঝে),Extrovert (বহির্মুখী),Sometimes (মাঝে মাঝে),Some Change (কিছুটা পরিবর্তন হয়),Negative Impact (নেতিবাচক প্রভাব),Sometimes (মাঝে মাঝে),Moderate Stress (মাঝারি চাপ অনুভব হয়),Slight Change in Sleep Quality (ঘুমের মান কিছু...,Lose Focus Frequently (অত্যধিক মনোযোগ হারায়),Sometimes Interested (মাঝে মাঝে আগ্রহ হয়)
1,28,Male(ছেলে),Islam (ইসলাম),Unmarried (অবিবাহিত),Urban Area (শহুরে এলাকা),Service Holder (চাকুরীজীবী),Joint Family (যৌথ পরিবার),10 min max,Very Good (খুবই ভালো),Neutral (নিরপেক্ষ),...,Never (কখনো না),Introvert (অন্তর্মুখী),Never (কখনো না),No Change (পরিবর্তন নেই),No Impact (কোনো প্রভাব পড়ে না),Never (কখনো না),No Stress (চাপ অনুভব হয় না),Not Sure (নিশ্চিত না),Do Not Lose Focus (মনোযোগ কমে না),Rarely Interested (খুব কম আগ্রহ হয়)
2,25,Female(মেয়ে),Islam (ইসলাম),Unmarried (অবিবাহিত),Urban Area (শহুরে এলাকা),Student (স্টুডেন্ট),Single family(একক পরিবার ),5/6,Very Good (খুবই ভালো),Somewhat Comfortable (কিছুটা স্বাচ্ছন্দ্যবোধ করি),...,Sometimes (মাঝে মাঝে),Introvert (অন্তর্মুখী),Always (সবসময়),Some Change (কিছুটা পরিবর্তন হয়),Not Sure (নিশ্চিত না),Sometimes (মাঝে মাঝে),No Stress (চাপ অনুভব হয় না),Not Sure (নিশ্চিত না),Lose Focus Sometimes (মাঝে মাঝে মনোযোগ হারায়),More Interest in Watching Reels (আরও রিলস দেখা...
3,25,Male(ছেলে),Islam (ইসলাম),Married (বিবাহিত),Urban Area (শহুরে এলাকা),Student (স্টুডেন্ট),Joint Family (যৌথ পরিবার),2/3 Hours,Moderate (মাঝারি),Very Comfortable (খুব স্বাচ্ছন্দ্যবোধ করি),...,Never (কখনো না),Ambivert (মাঝামাঝি),Sometimes (মাঝে মাঝে),Some Change (কিছুটা পরিবর্তন হয়),Not Sure (নিশ্চিত না),Never (কখনো না),No Stress (চাপ অনুভব হয় না),Not Sure (নিশ্চিত না),Do Not Lose Focus (মনোযোগ কমে না),Sometimes Interested (মাঝে মাঝে আগ্রহ হয়)
4,25,Female(মেয়ে),Islam (ইসলাম),Unmarried (অবিবাহিত),Urban Area (শহুরে এলাকা),Student (স্টুডেন্ট),Single family(একক পরিবার ),0,Good (ভালো),Neutral (নিরপেক্ষ),...,Sometimes (মাঝে মাঝে),Ambivert (মাঝামাঝি),Always (সবসময়),Some Change (কিছুটা পরিবর্তন হয়),Not Sure (নিশ্চিত না),Rarely (খুব কম),Low Stress (সামান্য চাপ অনুভব হয়),Slight Change in Sleep Quality (ঘুমের মান কিছু...,Lose Focus Rarely (খুব কম মনোযোগ হারায়),Sometimes Interested (মাঝে মাঝে আগ্রহ হয়)

In [122]:
# Remove Bangla text, keeping only the English part of each value
# Values look like "English text (বাংলা text)" -> keep "English text"
bangla_pattern = re.compile(r"\s*\([^()]*[ঀ-৿][^()]*\)")


def strip_bangla(value):
    if isinstance(value, str):
        cleaned = bangla_pattern.sub("", value)
        cleaned = re.sub(r"[ঀ-৿]+", "", cleaned)
        return cleaned.strip()
    return value


df = df.apply(lambda col: col.map(strip_bangla))
df.head()

,A1_age,A2_gender,A3_religion,A4_marital_status,A5_residence,A6_occupation,B1_family_type,B2_family_time_hours,B3_family_relationship,B4_in_person_feeling,...,G6_panic_attacks,G7_behavior_type,G8_addictive_watching,H1_mental_state_change,H2_content_type_effect,H3_distraction_after_viral,H4_brain_pressure,H5_sleep_quality_change,H6_emotional_reels_focus_loss,H7_curiosity_driven_rewatch
0,24,Male,Islam,Married,Urban Area,Student,Single family,3,Good,Somewhat Comfortable,...,Sometimes,Extrovert,Sometimes,Some Change,Negative Impact,Sometimes,Moderate Stress,Slight Change in Sleep Quality,Lose Focus Frequently,Sometimes Interested
1,28,Male,Islam,Unmarried,Urban Area,Service Holder,Joint Family,10 min max,Very Good,Neutral,...,Never,Introvert,Never,No Change,No Impact,Never,No Stress,Not Sure,Do Not Lose Focus,Rarely Interested
2,25,Female,Islam,Unmarried,Urban Area,Student,Single family,5/6,Very Good,Somewhat Comfortable,...,Sometimes,Introvert,Always,Some Change,Not Sure,Sometimes,No Stress,Not Sure,Lose Focus Sometimes,More Interest in Watching Reels
3,25,Male,Islam,Married,Urban Area,Student,Joint Family,2/3 Hours,Moderate,Very Comfortable,...,Never,Ambivert,Sometimes,Some Change,Not Sure,Never,No Stress,Not Sure,Do Not Lose Focus,Sometimes Interested
4,25,Female,Islam,Unmarried,Urban Area,Student,Single family,0,Good,Neutral,...,Sometimes,Ambivert,Always,Some Change,Not Sure,Rarely,Low Stress,Slight Change in Sleep Quality,Lose Focus Rarely,Sometimes Interested

In [123]:
# from ydata_profiling import ProfileReport

# profile = ProfileReport(
#     df,
#     title="Reels & Mental Health Survey - Full Dataset Profile",
#     explorative=True,
# )
# profile.to_notebook_iframe()

In [124]:
# Show all unique values (with counts) for every column as an HTML report
from html import escape
from IPython.display import HTML, display


def describe_value(value):
    """Return (label, css_class) so missing / blank / junk values stand out."""
    if pd.isna(value):
        return "NaN (missing)", "missing"
    text = str(value)
    if text.strip() == "":
        return f"'{text}' (blank)", "missing"
    if not re.search(r"[A-Za-z0-9]", text):
        return f"'{text}' (no letters/digits)", "junk"
    return text, ""


sections = []
for col in df.columns:
    counts = df[col].value_counts(dropna=False)
    n_missing = int(df[col].isna().sum() + (df[col].astype(str).str.strip() == "").sum())
    rows = "".join(
        f"<tr class='{cls}'><td>{escape(label)}</td><td class='num'>{count}</td></tr>"
        for label, cls, count in (
            (*describe_value(value), count) for value, count in counts.items()
        )
    )
    sections.append(
        f"<details {'open' if len(counts) <= 10 else ''}>"
        f"<summary><b>{escape(col)}</b> &mdash; {len(counts)} unique, "
        f"{n_missing} missing/blank</summary>"
        f"<table><tr><th>Value</th><th>Count</th></tr>{rows}</table></details>"
    )

style = """
<style>
.uv details { margin: 6px 0; border: 1px solid #8884; border-radius: 6px; padding: 6px 10px; }
.uv summary { cursor: pointer; }
.uv table { border-collapse: collapse; margin-top: 6px; min-width: 360px; }
.uv th, .uv td { border: 1px solid #8884; padding: 3px 8px; text-align: left; white-space: pre-wrap; }
.uv td.num { text-align: right; width: 60px; }
.uv tr.missing td { background: #e5484d33; }
.uv tr.junk td { background: #f5a52433; }
</style>
"""
display(HTML(
    style
    + f"<div class='uv'><p>{len(df)} rows &times; {len(df.columns)} columns. "
    "Red = missing/blank, orange = no letters/digits. "
    "Columns with more than 10 values are collapsed &mdash; click to expand.</p>"
    + "".join(sections)
    + "</div>"
))

## Value Handeling

In [125]:
# Cleaning helpers shared by every column below
# Rules: missing / unclear -> column mode | number + unit -> the number | sentences are NOT parsed (mode instead)
import numpy as np

df_before = df.copy()   # snapshot, used for the final comparison
clean_log = {}          # per-column statistics, filled by the cleaning functions

PLACEHOLDERS = {"", "n/a", "na", "n.a.", "null", "nan", "unknown", "not applicable", "not available", "nil"}


def is_missing_like(value):
    """NaN, blank string or a placeholder such as 'N/A' / 'unknown'."""
    return bool(pd.isna(value)) or str(value).strip().lower() in PLACEHOLDERS


def detect_type(series):
    values = series[~series.map(is_missing_like)].astype(str).str.strip()
    if set(values.str.lower().unique()) <= {"yes", "no", "true", "false"}:
        return "boolean"
    if values.nunique() <= 15:
        return "categorical"
    return "numerical" if values.str.contains(r"\d").mean() > 0.5 else "text"


def count_modified(before, after):
    if pd.api.types.is_numeric_dtype(after):
        same = pd.to_numeric(before.astype(str).str.strip(), errors="coerce").eq(after)
        return int((~same).sum())
    return int((before.astype("string").str.strip().fillna("<NA>") != after.astype("string")).sum())


def log_cleaning(col, ctype, before, after, missing, invalid, converted, mode):
    clean_log[col] = {
        "type": ctype,
        "modified": count_modified(before, after),
        "missing_replaced": int(missing),
        "invalid_replaced": int(invalid),
        "mixed_converted": int(converted),
        "mode_used": mode,
    }


def clean_categorical(col, valid=None):
    """Trim/standardise text, send missing + unclear values to the mode. Valid text is never changed."""
    raw = df[col]
    ctype = detect_type(raw)
    text = raw.astype("string").str.strip().str.replace(r"\s+", " ", regex=True)

    missing = raw.map(is_missing_like).astype(bool)
    # unclear = no letter/digit at all (e.g. "।", ",", "-"), or not one of the allowed values
    invalid = ~missing & ~text.str.contains(r"[A-Za-z0-9]", na=False).astype(bool)
    if valid is not None:
        invalid |= ~missing & ~text.str.lower().isin([v.lower() for v in valid]).astype(bool)

    text = text.mask(missing | invalid)
    key = text.str.lower()
    # one spelling per value = its most frequent spelling (Male / male / MALE -> Male)
    canonical = text.groupby(key).agg(lambda x: x.value_counts().idxmax())
    text = key.map(canonical)

    mode = text.mode().iloc[0]
    cleaned = text.fillna(mode).astype(str)
    df[col] = cleaned
    log_cleaning(col, ctype, raw, cleaned, missing.sum(), invalid.sum(), 0, mode)

    print(f"{col} | detected type: {ctype}")
    print(f"missing replaced: {missing.sum()} | invalid replaced: {invalid.sum()} | "
          f"modified: {clean_log[col]['modified']} | mode: {mode}")
    if invalid.any():
        print("invalid values:", raw[invalid].unique().tolist())
    summary = cleaned.value_counts().rename("count").to_frame()
    summary["percent"] = (summary["count"] / summary["count"].sum() * 100).round(1)
    display(summary)


# ---- numeric parsing -------------------------------------------------------
NUMBER = r"\d+(?:\.\d+)?"
QUALIFIERS = r"(?:(?:about|around|approximately|approx|almost|nearly|over|average|avg)\s+)?"
ZERO_WORDS = {"zero", "never", "none", "nil"}

# alias -> factor that converts it into the column's target unit
HOURS = {**dict.fromkeys(["h", "hr", "hrs", "hour", "hours", "houre", "hour's", "hours's", "gonta", "ghonta"], 1.0),
         **dict.fromkeys(["m", "min", "mins", "minute", "minutes"], 1 / 60)}
YEARS = {**dict.fromkeys(["y", "yr", "yrs", "year", "years", "yeasr"], 1.0),
         **dict.fromkeys(["month", "months"], 1 / 12),
         **dict.fromkeys(["week", "weeks"], 1 / 52)}
KILOS = dict.fromkeys(["kg", "kgs", "kilo", "kilos", "kilogram", "kilograms"], 1.0)


def make_quantity_parser(units, min_value, max_value):
    """Strict parser: the WHOLE value must be '<number> [unit]', a range ('5-6', '5/6') or 'N unit M unit'.
    Anything else (sentences, opinions, numbers hidden in text) is invalid -> None."""
    alias = "|".join(re.escape(u) for u in sorted(units, key=len, reverse=True))
    pattern = re.compile(
        rf"{QUALIFIERS}({NUMBER})(?:\s*(-|–|/|\\|to)\s*({NUMBER}))?\s*({alias})?(?:\s+({NUMBER})\s*({alias}))?"
    )

    def parse(value):
        t = str(value).strip().lower().rstrip(". ")
        if t in ZERO_WORDS:
            return 0.0, "converted"
        m = pattern.fullmatch(t)
        if not m:
            return None, "invalid"
        a, sep, b, unit, c, unit2 = m.groups()
        a, f = float(a), units[unit] if unit else 1.0
        if b:
            if sep == "/" and (a, float(b)) == (1.0, 2.0):      # "1/2 hour" - half an hour or 1-2 hours?
                return None, "invalid"
            amount, kind = (a + float(b)) / 2 * f, "range"
        elif c:
            amount, kind = a * f + float(c) * units[unit2], "converted"
        else:
            amount, kind = a * f, ("plain" if re.fullmatch(NUMBER, t) else "converted")
        return (amount, kind) if min_value <= amount <= max_value else (None, "invalid")

    return parse


FT = r"(?:'|\"|ft|feet|foot|fit)"
INCH = r"(?:\"|inches|inche|inch|inc|in)"


def parse_height_cm(value):
    """Height in cm. Understands cm, feet/inches (5'6", 5 feet 6 inch, 5.6) and inches-only (69 inch)."""
    t = str(value).strip().lower()
    for q in "’‘`´′":
        t = t.replace(q, "'")
    for q in "”“″":
        t = t.replace(q, '"')
    t = t.replace("''", '"').rstrip(". ")

    kind = "plain" if re.fullmatch(NUMBER, t) else "converted"
    cm = None

    m = re.fullmatch(rf"({NUMBER})\s*(?:cm|c\.m|centimeters?|centimetres?)", t) or re.search(rf"\(({NUMBER})\s*cm\)", t)
    if m:
        cm = float(m.group(1))
    elif (m := re.fullmatch(rf"({NUMBER})\s*(?:inches|inche|inch|inc|in|\")", t)) and float(m.group(1)) >= 48:
        cm = float(m.group(1)) * 2.54
    elif re.fullmatch(NUMBER, t):
        v = float(t)
        if 100 <= v <= 250:                                       # bare number in cm
            cm = v
        elif re.fullmatch(r"\d\.(?:\d{3,}|1[2-9]|[2-9]\d)", t):   # 5.75 -> decimal feet (inches can't exceed 11)
            cm = v * 30.48
        elif not re.fullmatch(r"\d\.\d{1,2}", t):                 # bare '5' or '55' is not a height
            return None, "invalid"
    if cm is None and t.count(".") < 2:
        m = re.fullmatch(rf"(\d)\s*(?:{FT})?\s*[.,:\-]?\s*(?:{FT})?\s*(\d{{1,2}}(?:\.\d+)?)?\s*(?:{INCH}|{FT})?", t)
        if m:
            feet, inches = float(m.group(1)), float(m.group(2) or 0)
            if inches < 12:
                cm = (feet * 12 + inches) * 2.54
    if cm is None or not 120 <= cm <= 230:
        return None, "invalid"
    return round(cm, 1), kind


def clean_numeric(col, parser, unit, integer=False):
    """Strict numeric cleaning: parseable -> number, missing/unclear -> mode."""
    raw = df[col]
    ctype = detect_type(raw)
    parsed, kinds = [], []
    for v in raw:
        if is_missing_like(v):
            parsed.append(np.nan)
            kinds.append("missing")
        else:
            val, kind = parser(v)
            parsed.append(np.nan if val is None else val)
            kinds.append(kind)
    parsed = pd.Series(parsed, index=raw.index, dtype=float).round(2)
    kinds = pd.Series(kinds, index=raw.index)

    mode = parsed.mode().iloc[0]
    cleaned = parsed.fillna(mode)
    if integer:                                  # whole numbers only (e.g. age)
        cleaned, mode = cleaned.astype(int), int(mode)
    df[col] = cleaned
    log_cleaning(col, "numerical", raw, cleaned, (kinds == "missing").sum(), (kinds == "invalid").sum(),
                 kinds.isin(["converted", "range"]).sum(), mode)

    print(f"{col} | detected type: {ctype} | target unit: {unit}")
    print(f"missing replaced: {(kinds == 'missing').sum()} | invalid replaced: {(kinds == 'invalid').sum()} | "
          f"text/unit converted: {(kinds == 'converted').sum()} | ranges -> midpoint: {(kinds == 'range').sum()} | mode: {mode}")
    changes = pd.DataFrame({"before": raw, "after": cleaned, "action": kinds})
    display(changes[changes["action"].isin(["invalid", "converted", "range"])].sort_values("action"))
    display(cleaned.describe().round(2).to_frame().T)


# ---- one entry point for every column --------------------------------------
def make_whole_number_parser(parser):
    """Wrap a parser so the result is floored to whole units (20 year 8.5 month -> 20)."""
    def parse(value):
        amount, kind = parser(value)
        return (float(np.floor(amount)), kind) if amount is not None else (None, kind)
    return parse


# Column-specific settings; any column not listed here is cleaned as a plain categorical column.
NUMERIC_RULES = {   # column: (parser, unit, whole numbers only?)
    "A1_age": (make_whole_number_parser(make_quantity_parser(YEARS, min_value=10, max_value=100)), "years", True),
    "B2_family_time_hours": (make_quantity_parser(HOURS, min_value=0, max_value=24), "hours", False),
    "C1_height": (parse_height_cm, "cm", False),
    "C2_weight": (make_quantity_parser(KILOS, min_value=30, max_value=200), "kg", False),
    "D1_years_watching": (make_quantity_parser(YEARS, min_value=0, max_value=10), "years", False),
}
ALLOWED_VALUES = {"A2_gender": ["Male", "Female"]}


def clean_column(col):
    """Clean any column with the same rules: numeric columns use their parser, the rest are categorical."""
    if col in NUMERIC_RULES:
        parser, unit, integer = NUMERIC_RULES[col]
        clean_numeric(col, parser, unit, integer)
    else:
        clean_categorical(col, valid=ALLOWED_VALUES.get(col))

## A1_age

In [126]:
# A1_age

In [127]:
# A1_age
clean_column("A1_age")

A1_age | detected type: numerical | target unit: years
missing replaced: 4 | invalid replaced: 1 | text/unit converted: 6 | ranges -> midpoint: 0 | mode: 25

                before  after     action
17            22 years     22  converted
34             25years     25  converted
75            24 years     24  converted
117  20 year 8.5 month     20  converted
150           25 years     25  converted
415            27 year     27  converted
410       Ratul Halder     25    invalid

   count   mean   std   min   25%   50%   75%   max
0  506.0  25.13  4.11  16.0  22.0  24.0  27.0  35.0

In [128]:
# A1_age -  groups
# 16-20 | 21-25 | 26-35 (right-inclusive bins)
bins = [0, 20, 25, df["A1_age"].max()]
labels = ["16-20", "21-25", "26-35"]

df["A1_age_group"] = pd.cut(df["A1_age"], bins=bins, labels=labels, right=True)

summary = (
    df["A1_age_group"].value_counts().reindex(labels).rename("count").to_frame()
    .assign(percent=lambda t: (t["count"] / t["count"].sum() * 100).round(1))
)
display(summary)
print("missing:", df["A1_age_group"].isna().sum())

              count  percent
A1_age_group
16-20            42      8.3
21-25           305     60.3
26-35           159     31.4

missing: 0

## A2_gender

In [129]:
# A2_gender
clean_column("A2_gender")

A2_gender | detected type: categorical
missing replaced: 2 | invalid replaced: 0 | modified: 2 | mode: Male

           count  percent
A2_gender
Male         337     66.6
Female       169     33.4

## A3_religion

In [130]:
# A3_religion
clean_column("A3_religion")

A3_religion | detected type: categorical
missing replaced: 3 | invalid replaced: 0 | modified: 3 | mode: Islam

             count  percent
A3_religion
Islam          491     97.0
Hindu           12      2.4
Christian        3      0.6

## A4_marital_status

In [131]:
# A4_marital_status
clean_column("A4_marital_status")

A4_marital_status | detected type: categorical
missing replaced: 2 | invalid replaced: 0 | modified: 2 | mode: Unmarried

                   count  percent
A4_marital_status
Unmarried            327     64.6
Married              174     34.4
Divorced               5      1.0

## A5_residence

In [132]:
# A5_residence
clean_column("A5_residence")

A5_residence | detected type: categorical
missing replaced: 3 | invalid replaced: 0 | modified: 3 | mode: Urban Area

              count  percent
A5_residence
Urban Area      296     58.5
Rural Area      210     41.5

## A6_occupation

In [133]:
# A6_occupation
clean_column("A6_occupation")

A6_occupation | detected type: categorical
missing replaced: 3 | invalid replaced: 0 | modified: 3 | mode: Student

                count  percent
A6_occupation
Student           319     63.0
Service Holder     73     14.4
Others             70     13.8
Businessperson     44      8.7

## B1_family_type

In [134]:
# B1_family_type
clean_column("B1_family_type")

B1_family_type | detected type: categorical
missing replaced: 2 | invalid replaced: 0 | modified: 2 | mode: Single family

                       count  percent
B1_family_type
Single family            313     61.9
Joint Family             183     36.2
Extended Family            6      1.2
Joint Extended Family      4      0.8

## B2_family_time_hours

In [135]:
# B2_family_time_hours
clean_column("B2_family_time_hours")

B2_family_time_hours | detected type: numerical | target unit: hours
missing replaced: 10 | invalid replaced: 23 | text/unit converted: 43 | ranges -> midpoint: 41 | mode: 2.0

        before  after     action
107   12 hours   12.0  converted
110       2hrs    2.0  converted
57     4 hours    4.0  converted
60          2h    2.0  converted
66      5hours    5.0  converted
..         ...    ...        ...
104  6/7 hours    6.5      range
155        2-3    2.5      range
164        2-3    2.5      range
137  4/5 hours    4.5      range
491        5/6    5.5      range

[107 rows x 3 columns]

   count  mean   std  min  25%  50%  75%   max
0  506.0  5.44  4.75  0.0  2.0  4.0  7.0  24.0

## B3_family_relationship

In [136]:
# B3_family_relationship
clean_column("B3_family_relationship")

B3_family_relationship | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: Very Good

                        count  percent
B3_family_relationship
Very Good                 322     63.6
Good                      131     25.9
Moderate                   48      9.5
Bad                         4      0.8
Very Bad                    1      0.2

## B4_in_person_feeling

In [137]:
# B4_in_person_feeling
clean_column("B4_in_person_feeling")

B4_in_person_feeling | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: Very Comfortable

                        count  percent
B4_in_person_feeling
Very Comfortable          190     37.5
Neutral                   139     27.5
Somewhat Comfortable      128     25.3
Somewhat Uncomfortable     42      8.3
Very Uncomfortable          7      1.4

## C1_height

In [138]:
# C1_height
clean_column("C1_height")

C1_height | detected type: numerical | target unit: cm
missing replaced: 8 | invalid replaced: 31 | text/unit converted: 182 | ranges -> midpoint: 0 | mode: 167.6

                before  after     action
1                 5'6"  167.6  converted
212  177.8 centimeters  177.8  converted
213             168 cm  168.0  converted
215               5'7"  170.2  converted
216               5.6"  167.6  converted
..                 ...    ...        ...
176                  5  167.6    invalid
159                  5  167.6    invalid
158                  5  167.6    invalid
379                  5  167.6    invalid
371                  6  167.6    invalid

[213 rows x 3 columns]

   count   mean   std    min    25%    50%    75%    max
0  506.0  166.2  7.95  124.5  160.0  167.6  170.2  190.5

## C2_weight

In [139]:
# C2_weight
clean_column("C2_weight")

C2_weight | detected type: numerical | target unit: kg
missing replaced: 7 | invalid replaced: 4 | text/unit converted: 53 | ranges -> midpoint: 1 | mode: 70.0

           before  after     action
3            80Kg   80.0  converted
137          65kg   65.0  converted
140         50 kg   50.0  converted
141          72kg   72.0  converted
146         41 kg   41.0  converted
148         70 kg   70.0  converted
149          48kg   48.0  converted
178          66kg   66.0  converted
182          56kg   56.0  converted
222         75 kg   75.0  converted
258          49kg   49.0  converted
277          42kg   42.0  converted
279          83kg   83.0  converted
292          70kg   70.0  converted
341          58kg   58.0  converted
346          58kg   58.0  converted
348          49kg   49.0  converted
352          46kg   46.0  converted
400          63kg   63.0  converted
401          85kg   85.0  converted
403          51kg   51.0  converted
409         60 kg   60.0  converted
410          62kg   62.0  converted
413         53 kg   53.0  converted
419         73 KG   73.0  converted
428         85 kg   85.0  converted
134         65 kg   65.0  converted
438          70kg   70.0  converted
439         82 kg   82.0  converted
75          56 kg   56.0  converted
50           62kg   62.0  converted
18          60 kg   60.0  converted
5            67kg   67.0  converted
60           63kg   63.0  converted
63          112kg  112.0  converted
66           46kg   46.0  converted
72           60kg   60.0  converted
127         58 kg   58.0  converted
77           45kg   45.0  converted
79          77 kg   77.0  converted
80          50 kg   50.0  converted
82           66Kg   66.0  converted
85           76kg   76.0  converted
96           94kg   94.0  converted
114          68kg   68.0  converted
117       62.8 kg   62.8  converted
118          69kg   69.0  converted
4           41 kg   41.0  converted
122         58 kg   58.0  converted
124          52KG   52.0  converted
125          79kg   79.0  converted
37           53kg   53.0  converted
34           70kg   70.0  converted
126             ।   70.0    invalid
59            75+   70.0    invalid
144         5"11'   70.0    invalid
57   5 fit 1 inch   70.0    invalid
130       67-68kg   67.5      range

   count   mean   std   min   25%   50%   75%    max
0  506.0  62.97  13.1  35.0  54.0  62.0  70.0  169.0

## C3_sitting_duration

In [140]:
# C3_sitting_duration
clean_column("C3_sitting_duration")

C3_sitting_duration | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: 30 minutes–1 hour

                      count  percent
C3_sitting_duration
30 minutes–1 hour       170     33.6
Less than 30 minutes    136     26.9
More than 2 hours       103     20.4
1–2 hours                97     19.2

## C4_physical_problems

In [141]:
# C4_physical_problems
clean_column("C4_physical_problems")

C4_physical_problems | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: Sometimes

                      count  percent
C4_physical_problems
Sometimes               225     44.5
Rarely                  119     23.5
Never                    91     18.0
Often                    71     14.0

## D1_years_watching

In [142]:
# D1_years_watching
clean_column("D1_years_watching")

D1_years_watching | detected type: numerical | target unit: years
missing replaced: 10 | invalid replaced: 17 | text/unit converted: 62 | ranges -> midpoint: 18 | mode: 4.0

        before  after     action
15     3 years    3.0  converted
144    5 years    5.0  converted
137    4 years    4.0  converted
136    8 years    8.0  converted
135      2 yrs    2.0  converted
..         ...    ...        ...
215        4\5    4.5      range
50         5-6    5.5      range
213  3/4 years    3.5      range
119        2-3    2.5      range
505        2/3    2.5      range

[97 rows x 3 columns]

   count  mean   std  min  25%  50%  75%   max
0  506.0  3.45  1.68  0.0  2.0  3.5  4.0  10.0

## D2_daily_watch_time

In [143]:
# D2_daily_watch_time
clean_column("D2_daily_watch_time")

D2_daily_watch_time | detected type: categorical
missing replaced: 3 | invalid replaced: 0 | modified: 3 | mode: 2 hours

                     count  percent
D2_daily_watch_time
2 hours                135     26.7
Less than 1 hour       110     21.7
1 hour                 108     21.3
More than that          95     18.8
3 hours                 58     11.5

## D3_peak_watch_time

In [144]:
# D3_peak_watch_time
clean_column("D3_peak_watch_time")

D3_peak_watch_time | detected type: categorical
missing replaced: 2 | invalid replaced: 0 | modified: 2 | mode: Before Sleeping

                    count  percent
D3_peak_watch_time
Before Sleeping       212     41.9
Leisure Time          189     37.4
During Work Break      58     11.5
Afternoon              20      4.0
Before Study           15      3.0
Morning                12      2.4

## D4_multitasking_while_watching

In [145]:
# D4_multitasking_while_watching
clean_column("D4_multitasking_while_watching")

D4_multitasking_while_watching | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Sometimes

                                count  percent
D4_multitasking_while_watching
Sometimes                         212     41.9
No                                168     33.2
Yes, frequently                   126     24.9

## E1_sleep_hours

In [146]:
# E1_sleep_hours
clean_column("E1_sleep_hours")

E1_sleep_hours | detected type: categorical
missing replaced: 3 | invalid replaced: 0 | modified: 3 | mode: 6–8 hours

                   count  percent
E1_sleep_hours
6–8 hours            345     68.2
Less than 6 hours     98     19.4
More than 8 hours     63     12.5

## E2_sleep_trouble

In [147]:
# E2_sleep_trouble
clean_column("E2_sleep_trouble")

E2_sleep_trouble | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: No

                  count  percent
E2_sleep_trouble
No                  254     50.2
Sometimes           158     31.2
Yes                  94     18.6

## E3_exercise_involvement

In [148]:
# E3_exercise_involvement
clean_column("E3_exercise_involvement")

E3_exercise_involvement | detected type: categorical
missing replaced: 3 | invalid replaced: 0 | modified: 3 | mode: Sometimes

                         count  percent
E3_exercise_involvement
Sometimes                  194     38.3
Rarely                     146     28.9
Never                       93     18.4
Regularly                   73     14.4

## E4_substance_use

In [149]:
# E4_substance_use
clean_column("E4_substance_use")

E4_substance_use | detected type: categorical
missing replaced: 3 | invalid replaced: 0 | modified: 3 | mode: No

                   count  percent
E4_substance_use
No                   348     68.8
Yes                  103     20.4
Sometimes             26      5.1
Used to do before     15      3.0
Prefer not to say     14      2.8

## F1_attention_decreased

In [150]:
# F1_attention_decreased
clean_column("F1_attention_decreased")

F1_attention_decreased | detected type: categorical
missing replaced: 3 | invalid replaced: 0 | modified: 3 | mode: Decreased a little

                         count  percent
F1_attention_decreased
Decreased a little         226     44.7
Decreased a lot            153     30.2
Did not decrease            95     18.8
Did not decrease at all     32      6.3

## F2_memory_reduced

In [151]:
# F2_memory_reduced
clean_column("F2_memory_reduced")

F2_memory_reduced | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: Decreased a little

                         count  percent
F2_memory_reduced
Decreased a little         212     41.9
Did not decrease           146     28.9
Decreased a lot            107     21.1
Did not decrease at all     41      8.1

## F3_learning_interest_decreased

In [152]:
# F3_learning_interest_decreased
clean_column("F3_learning_interest_decreased")

F3_learning_interest_decreased | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Did not decrease

                                count  percent
F3_learning_interest_decreased
Did not decrease                  194     38.3
Decreased a little                168     33.2
Decreased a lot                    90     17.8
Did not decrease at all            54     10.7

## F4_performance_affected

In [153]:
# F4_performance_affected
clean_column("F4_performance_affected")

F4_performance_affected | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Somewhat negative

                         count  percent
F4_performance_affected
Somewhat negative          231     45.7
No effect                  129     25.5
Very negative              101     20.0
Somewhat positive           32      6.3
Very positive               13      2.6

## G1_mood_swings

In [154]:
# G1_mood_swings
clean_column("G1_mood_swings")

G1_mood_swings | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: Sometimes

                count  percent
G1_mood_swings
Sometimes         238     47.0
Often             140     27.7
Always             73     14.4
Never              55     10.9

## G2_fomo_anxiety

In [155]:
# G2_fomo_anxiety
clean_column("G2_fomo_anxiety")

G2_fomo_anxiety | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: Never

                 count  percent
G2_fomo_anxiety
Never              278     54.9
Sometimes          141     27.9
Often               62     12.3
Always              25      4.9

## G3_social_comparison

In [156]:
# G3_social_comparison
clean_column("G3_social_comparison")

G3_social_comparison | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: No

                      count  percent
G3_social_comparison
No                      287     56.7
Sometimes               166     32.8
Yes, frequently          53     10.5

## G4_social_isolation

In [157]:
# G4_social_isolation
clean_column("G4_social_isolation")

G4_social_isolation | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: No

                     count  percent
G4_social_isolation
No                     330     65.2
Sometimes              137     27.1
Yes, frequently         39      7.7

## G5_mental_stress

In [158]:
# G5_mental_stress
clean_column("G5_mental_stress")

G5_mental_stress | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: No

                  count  percent
G5_mental_stress
No                  278     54.9
Yes                 117     23.1
Not Sure            111     21.9

## G6_panic_attacks

In [159]:
# G6_panic_attacks
clean_column("G6_panic_attacks")

G6_panic_attacks | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Never

                  count  percent
G6_panic_attacks
Never               234     46.2
Sometimes           137     27.1
Very Rarely         103     20.4
Yes, regularly       32      6.3

## G7_behavior_type

In [160]:
# G7_behavior_type
clean_column("G7_behavior_type")

G7_behavior_type | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Ambivert

                  count  percent
G7_behavior_type
Ambivert            290     57.3
Extrovert           112     22.1
Introvert           104     20.6

## G8_addictive_watching

In [161]:
# G8_addictive_watching
clean_column("G8_addictive_watching")

G8_addictive_watching | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Never

                       count  percent
G8_addictive_watching
Never                    133     26.3
Sometimes                128     25.3
Often                    111     21.9
Very Rarely               83     16.4
Always                    51     10.1

## H1_mental_state_change

In [162]:
# H1_mental_state_change
clean_column("H1_mental_state_change")

H1_mental_state_change | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Some Change

                        count  percent
H1_mental_state_change
Some Change               235     46.4
No Change                 163     32.2
Not Sure                   76     15.0
Major Change               32      6.3

## H2_content_type_effect

In [163]:
# H2_content_type_effect
clean_column("H2_content_type_effect")

H2_content_type_effect | detected type: categorical
missing replaced: 6 | invalid replaced: 0 | modified: 6 | mode: Not Sure

                        count  percent
H2_content_type_effect
Not Sure                  168     33.2
Negative Impact           137     27.1
No Impact                 115     22.7
Positive Impact            86     17.0

## H3_distraction_after_viral

In [164]:
# H3_distraction_after_viral
clean_column("H3_distraction_after_viral")

H3_distraction_after_viral | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Sometimes

                            count  percent
H3_distraction_after_viral
Sometimes                     193     38.1
Never                         146     28.9
Rarely                        103     20.4
Often                          64     12.6

## H4_brain_pressure

In [ ]:
# H4_brain_pressure
clean_column("H4_brain_pressure")

H4_brain_pressure | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: No Stress

                   count  percent
H4_brain_pressure
No Stress            234     46.2
Moderate Stress      127     25.1
Low Stress           117     23.1
High Stress           28      5.5

## H5_sleep_quality_change

In [ ]:
# H5_sleep_quality_change
clean_column("H5_sleep_quality_change")

H5_sleep_quality_change | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Slight Change in Sleep Quality

                                count  percent
H5_sleep_quality_change
Slight Change in Sleep Quality    162     32.0
Sleep Quality Unchanged           139     27.5
Not Sure                          137     27.1
Poor Sleep Quality                 68     13.4

## H6_emotional_reels_focus_loss

In [ ]:
# H6_emotional_reels_focus_loss
clean_column("H6_emotional_reels_focus_loss")

H6_emotional_reels_focus_loss | detected type: categorical
missing replaced: 5 | invalid replaced: 0 | modified: 5 | mode: Lose Focus Sometimes

                               count  percent
H6_emotional_reels_focus_loss
Lose Focus Sometimes             202     39.9
Do Not Lose Focus                141     27.9
Lose Focus Frequently             83     16.4
Lose Focus Rarely                 80     15.8

## H7_curiosity_driven_rewatch

In [ ]:
# H7_curiosity_driven_rewatch
clean_column("H7_curiosity_driven_rewatch")

H7_curiosity_driven_rewatch | detected type: categorical
missing replaced: 4 | invalid replaced: 0 | modified: 4 | mode: Sometimes Interested

                                 count  percent
H7_curiosity_driven_rewatch
Sometimes Interested               182     36.0
More Interest in Watching Reels    165     32.6
Not Interested                      92     18.2
Rarely Interested                   67     13.2